name: flutter_workspaces_cli
description: A sample command-line application.
version: 1.0.0
publish_to: https://pub.dev
repository: https://github.com/ThiagoEvoa/flutter_workspaces_cli

environment:
  sdk: ^3.10.8

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
